# ===========================================
# Image Moderation API - Security Configuration
# ===========================================

security:
  # Authentication
  auth:
    token_expiry_days: 90
    min_token_length: 32
    require_bearer_prefix: true
    rate_limit:
      requests_per_minute: 100
      burst_limit: 200

  # API Security
  api:
    cors:
      allowed_origins:
        - "http://localhost:3000"
        - "https://yourdomain.com"
      allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowed_headers: ["Authorization", "Content-Type", "Accept"]
      max_age: 86400

    rate_limiting:
      default_limit: "100/minute"
      moderation_limit: "50/minute"
      upload_limit: "20/minute"

    file_uploads:
      max_file_size: "10MB"
      allowed_extensions: [".jpg", ".jpeg", ".png", ".gif", ".webp"]
      allowed_mime_types:
        - "image/jpeg"
        - "image/png"
        - "image/gif"
        - "image/webp"
      virus_scanning: false # Enable if clamav is available

    headers:
      x_frame_options: "DENY"
      x_content_type_options: "nosniff"
      x_xss_protection: "1; mode=block"
      strict_transport_security: "max-age=31536000; includeSubDomains"
      content_security_policy: "default-src 'self'"
      referrer_policy: "strict-origin-when-cross-origin"

  # Database Security
  database:
    connection:
      ssl: false # Enable for production
      auth_source: "admin"
      read_preference: "primary"

    access_control:
      enable_role_based_access: true
      audit_logging: true
      connection_timeout: 30000

    backup:
      encryption: false # Enable for sensitive data
      retention_days: 30
      max_backups: 50

  # Container Security
  docker:
    user: "1000:1000" # Non-root user
    read_only_root: false
    no_new_privileges: true
    security_opts:
      - "no-new-privileges:true"
    tmpfs:
      - "/tmp:noexec,nosuid,size=100m"

    resource_limits:
      memory: "2g"
      cpus: "1.0"
      pids_limit: 1000

  # AI/ML Security
  ai_models:
    input_validation:
      max_image_size: "10MB"
      max_dimensions: "4096x4096"
      allowed_formats: ["JPEG", "PNG", "GIF", "WebP"]

    output_filtering:
      confidence_threshold: 0.30
      sanitize_metadata: true
      log_high_risk_content: true

    model_protection:
      disable_model_inspection: true
      rate_limit_inference: true
      monitor_resource_usage: true

  # Logging & Monitoring
  logging:
    level: "INFO"
    format: "json"
    include_request_id: true
    log_sensitive_data: false

    audit_events:
      - "authentication_failure"
      - "authorization_failure"
      - "high_risk_content_detected"
      - "rate_limit_exceeded"
      - "suspicious_activity"

    retention:
      log_retention_days: 90
      audit_retention_days: 365

  # Environment Security
  environment:
    production:
      debug: false
      testing: false
      detailed_errors: false

    secrets_management:
      use_environment_variables: true
      encrypt_secrets_at_rest: false
      rotate_secrets_regularly: true

    network:
      bind_host: "0.0.0.0" # Use specific IP in production
      allowed_ips: [] # Restrict if needed
      use_proxy: false

# Compliance Settings
compliance:
  gdpr:
    data_retention_days: 30
    anonymize_logs: true
    user_data_deletion: true

  privacy:
    log_user_ips: false
    store_uploaded_images: false
    cache_results: true
    cache_ttl_minutes: 60

# Alerting Thresholds
alerts:
  security:
    failed_auth_attempts: 10
    suspicious_upload_patterns: 20
    rate_limit_violations: 50

  performance:
    response_time_threshold: 30 # seconds
    error_rate_threshold: 5 # percentage
    memory_usage_threshold: 80 # percentage

  business:
    high_risk_content_threshold: 10 # per hour
    unusual_traffic_patterns: 100 # requests per minute

# Development vs Production
profiles:
  development:
    debug: true
    detailed_errors: true
    cors_any_origin: true
    disable_rate_limiting: true

  production:
    debug: false
    detailed_errors: false
    cors_strict: true
    enable_all_security_headers: true
    require_https: true
    enable_monitoring: true
