version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: image_moderation_db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${DB_NAME:-image_moderation}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app_network

  api:
    build: .
    container_name: image_moderation_api
    restart: unless-stopped
    ports:
      - "7000:7000"
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/image_moderation?authSource=admin
      - DB_NAME=image_moderation
    depends_on:
      - mongodb
    volumes:
      - ./app:/app/app
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: image_moderation_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:7000
    depends_on:
      - api
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge
